Requesting Notification Permission
k0shk0sh/PermissionHelper pull request #38
Opened 2018-05-24 06:41 UTC by rammadogs

My fork adds the ability to request permissions to manage notifications, which allows the app to do things such as switching off do not disturb mode.

2018-05-24 06:43 UTC, k0shk0sh requested changes
Please fix the unwanted stuff

2018-05-24 06:43 UTC, k0shk0sh commented on permission/build.gradle
> +group='com.github.rammadogs'
May I know wht did you add this?
Could you please remove everything related

2018-05-24 06:43 UTC, k0shk0sh commented on build.gradle
> +        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
This should be removed as well

2018-05-24 06:43 UTC, k0shk0sh commented on permission/build.gradle
> +apply plugin: 'com.github.dcendents.android-maven'
This as well

2018-05-25 03:54 UTC, rammadogs commented
Those changes were necessary to make it work with Jitpack. I need that working for a university assignment so when the assignment's over in a couple of weeks, I'll make the changes :)

2018-05-25 05:16 UTC, k0shk0sh commented
If that's the case then use ur own fork for your assignment and then resubmit another pr. I can't accept this.

2018-05-25 05:16 UTC, closed without merging